<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ejercicio1.aspx.cs" Inherits="TP6_GRUPO_2.WebForms.Ejercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="../Css/Estilos.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <h1 class="nomargen">Productos</h1>
        <asp:GridView ID="gvProductos" runat="server" AutoGenerateColumns="False" AllowPaging="True" OnPageIndexChanging="gvProductos_PageIndexChanging" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="gvProductos_RowCancelingEdit" OnRowDeleting="gvProductos_RowDeleting" OnRowEditing="gvProductos_RowEditing" OnRowUpdating="gvProductos_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="Id Producto">
                    <EditItemTemplate>
                        <asp:Label ID="lbl_eit_idProducto" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_IdProducto" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Nombre Producto">
                    <EditItemTemplate>
                        <asp:TextBox ID="txt_eit_nombreProducto" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="rfvNombreProducto" runat="server" ControlToValidate="txt_eit_nombreProducto" ErrorMessage="Ingrese un Nombre "></asp:RequiredFieldValidator>
                        <br />
                        <asp:RegularExpressionValidator ID="revNombre" runat="server" ControlToValidate="txt_eit_nombreProducto" ErrorMessage="Ingrese un Nombre Valido" ValidationExpression="^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$"></asp:RegularExpressionValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_NombreProducto" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Cantidad Por Unidad">
                    <EditItemTemplate>
                        <asp:TextBox ID="txt_eit_cantidadXunidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="rfvCantidadProducto" runat="server" ControlToValidate="txt_eit_cantidadXunidad" ErrorMessage="Ingrese una Cantidad"></asp:RequiredFieldValidator>
                        <br />
                        <asp:RegularExpressionValidator ID="revCantidad" runat="server" ControlToValidate="txt_eit_cantidadXunidad" ErrorMessage="Ingrese una Cantidad Valida" ValidationExpression="^[a-zA-Z0-9\s\-\.]+$"></asp:RegularExpressionValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_CantidadPorUnidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Precio Unidad">
                    <EditItemTemplate>
                        <asp:TextBox ID="txt_eit_precioUnidad" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="rfvPrecioUnidad" runat="server" ControlToValidate="txt_eit_precioUnidad" ErrorMessage="Ingrese un Precio"></asp:RequiredFieldValidator>
                        <br />
                        <asp:RegularExpressionValidator ID="revPrecioUnidad" runat="server" ControlToValidate="txt_eit_precioUnidad" ErrorMessage="Ingrese un Precio valido (ej: 30.50 o 30,50)" ValidationExpression="^[0-9]+([.,][0-9]+)?$"></asp:RegularExpressionValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_PrecioUnitario" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <br />
        <asp:HyperLink ID="hlInicio" runat="server" NavigateUrl="~/WebForms/Inicio.aspx">Volver a Inicio.Aspx</asp:HyperLink>
        <br />
    </form>
</body>
</html>
